In [1]:
import numpy

In [3]:
numbers_list = [1, 2, 3, 4, 5]

In [4]:
numbers_array = numpy.array(numbers_list)

In [5]:
type(numbers_list)

list

In [6]:
type(numbers_array)

numpy.ndarray

In [11]:
numbers_array.std()

1.4142135623730951

In [12]:
numbers_array * 5

array([ 5, 10, 15, 20, 25])

In [17]:
numbers_list.append(10)

In [18]:
numbers_list

[1, 2, 3, 4, 5, 10]

# This is heading 1

## Heading 

This is **bold** text. And this is *italic*

<h1> Heading </h1>


In [19]:
numbers_array_2 = numpy.array([6,7,8,9,0])

In [21]:
print(numbers_array)
print(numbers_array_2)

[1 2 3 4 5]
[6 7 8 9 0]


In [20]:
numbers_array + numbers_array_2

array([ 7,  9, 11, 13,  5])

In [22]:
numbers_array * numbers_array_2

array([ 6, 14, 24, 36,  0])

# Selection

In [25]:
numbers_array[1]

2

In [27]:
numbers_array[3:]

array([4, 5])

In [28]:
# everything except position 4
numbers_array[:4] 


array([1, 2, 3, 4])